/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ILSP7DigitalAsset } from "./ILSP7DigitalAsset";
export type { LSP7DigitalAsset } from "./LSP7DigitalAsset";
export type { LSP7DigitalAssetCore } from "./LSP7DigitalAssetCore";
