/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILSP1UniversalReceiverDelegate,
  ILSP1UniversalReceiverDelegateInterface,
} from "../../../../../@lukso/lsp-smart-contracts/contracts/LSP1UniversalReceiver/ILSP1UniversalReceiverDelegate";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "typeId",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "universalReceiverDelegate",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILSP1UniversalReceiverDelegate__factory {
  static readonly abi = _abi;
  static createInterface(): ILSP1UniversalReceiverDelegateInterface {
    return new Interface(_abi) as ILSP1UniversalReceiverDelegateInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ILSP1UniversalReceiverDelegate {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ILSP1UniversalReceiverDelegate;
  }
}
