/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ILSP1UniversalReceiver__factory } from "./ILSP1UniversalReceiver__factory";
export { ILSP1UniversalReceiverDelegate__factory } from "./ILSP1UniversalReceiverDelegate__factory";
