/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ILSP1UniversalReceiver } from "./ILSP1UniversalReceiver";
export type { ILSP1UniversalReceiverDelegate } from "./ILSP1UniversalReceiverDelegate";
